### ISSUE TITLE
Comparative benchmarking with the standard encoding/xml package?

### ISSUE THREAD

**Issue by vinser** [orisano/gosax#10]
Hi,

Have you done any comparative benchmarking with the standard encoding/xml package? I don't know about memory consumption, but in terms of performance I have doubts that gosax package works faster.

Trying to speed up my application that reads book titles in FB2 format (pure xml), I refactored all the code that parses book descriptions (authors, titles, contents, etc.) to replace the standard package with gosax. The result was discouraging. To my regret I did not get any gain in parsing speed on the same data. Processing 25 thousand test files took 23 seconds when using the standard package vs 30 seconds when using gosax. And this is despite the fact that I did not change the processing logic.

Are there any special features of using gosax or designs that should be avoided? I didn't use Compatibility with encoding/xml functions in my code.

Bests!

**Comment by orisano** [comment]
Thank you for your feedback and for sharing your experience with gosax. Performance can indeed vary significantly depending on usage patterns and specific workloads, so it's difficult to draw conclusions without seeing detailed profiling results. As a developer, I'm very interested in cases where gosax might be slower than encoding/xml, as this helps us improve the library.
In the case study mentioned in https://github.com/orisano/gosax/issues/3, we observed performance improvements. However, your experience is valuable data for us to consider.
To help us better understand your specific case, could you please share the profiling results? You can easily obtain these using code similar to the following:

```go
func BenchmarkXML(b *testing.B) {
     for i := 0; i < b.N; i++ {
          // your code
     }
}
```
```bash
go test -bench . -cpuprofile=cpu.pb.gz 
```
Once you have the profiling data, please share it with us. This will allow us to analyze the performance characteristics in your specific use case and potentially identify areas for optimization or improvement in gosax.
We appreciate your contribution to improving gosax, and we look forward to investigating this further with your help.

**Comment by vinser** [comment]
Dear @orisano thank you for your gosax package and suggestions for benchmark.
 
Before writing this benchmark, I should estimate the effort required for such testing, since the code of my project, although divided into packages, is quite large and non-trivial. The latest stable release using encoding/xml is here https://github.com/vinser/flibgolite. Its refactoring to gosax took me a month and a half, considering that I do it in my free time. 

At a first glance, it looks like for such comparative benchmark using standard golang testing packages, I will have to write two prototypes that parse data in a similar way to my project. One for the current release with encoding/xml, and the other using gosax. I am not sure that I will be able to allocate so much time for this, but I will think about it. 
It's very tempting to speed up the parsing twice as it was mentioned in #3  :)

In the meantime, please label this issue #4 as something like "help wanted"

**Comment by orisano** [comment]
Could you push the branch you refactored with gosax?

**Comment by orisano** [comment]
I took the initiative to implement FB2 parsing using gosax in the flibgolite project. You can find the implementation here:
https://github.com/orisano/flibgolite/commit/09bfec7987fb5e93de4a24a7457fe7d9c8ff56fc

Initially, when using gosax without any optimizations, the performance was indeed slower than encoding/xml, confirming the report you received. It's important to note that gosax.Reader is designed to be reused. However, given the interface of ParseFB2, direct reuse was challenging.
To address this, I implemented a solution using sync.Pool and gosax.NewReaderBuf to facilitate buffer reuse. Additionally, I made some minor adjustments to buffer sizes. These optimizations resulted in a significant performance improvement, with the new implementation running about three times faster than the existing one.
Here are the benchmark results from my environment:
```
goos: darwin
goarch: arm64
pkg: github.com/vinser/flibgolite/pkg/fb2
cpu: Apple M2 Max
BenchmarkParseFB2/encoding/xml-12         	   58815	     17550 ns/op
BenchmarkParseFB2/encoding/xml-12         	   67698	     17668 ns/op
BenchmarkParseFB2/encoding/xml-12         	   67536	     17569 ns/op
BenchmarkParseFB2/encoding/xml-12         	   67436	     17779 ns/op
BenchmarkParseFB2/encoding/xml-12         	   66927	     17685 ns/op
BenchmarkParseFB2/gosax-12                	  262652	      4621 ns/op
BenchmarkParseFB2/gosax-12                	  250389	      4663 ns/op
BenchmarkParseFB2/gosax-12                	  258180	      4712 ns/op
BenchmarkParseFB2/gosax-12                	  260504	      4731 ns/op
BenchmarkParseFB2/gosax-12                	  259719	      4725 ns/op
PASS
```

**Comment by vinser** [comment]
> Could you push the branch you refactored with gosax?

Branch [gosax](https://github.com/vinser/flibgolite/tree/gosax) was pushed

**Comment by vinser** [comment]
> I took the initiative to implement FB2 parsing using gosax in the flibgolite project. You can find the implementation here: [orisano/flibgolite@09bfec7](https://github.com/orisano/flibgolite/commit/09bfec7987fb5e93de4a24a7457fe7d9c8ff56fc)
Impressive result!!! 
In my environment, your example benchmark turns out to be almost more than four times faster
```
goos: linux
goarch: arm64
pkg: github.com/vinser/flibgolite/pkg/fb2
BenchmarkParseFB2/encoding/xml-8         	    3406	    403074 ns/op	   49216 B/op	     707 allocs/op
BenchmarkParseFB2/gosax-8                	   12819	    101681 ns/op	   15642 B/op	     366 allocs/op
PASS
```
As about my refactor fail, I was scared by the Note ))
>Note: For performance-critical applications, it's recommended to use the direct conversion functions (StartElement, EndElement, CharData, etc.) instead of Token, as they allow better control over memory allocations.

Everything was much simpler, it was just enough to replace the functions Token and Skip. 
I will throw away my unsuccessful branch and with your permission use your example from the benchmark

Thank you very much @orisano for your help!

**Comment by orisano** [comment]
@vinser As mentioned in the Note, by actually writing the program to avoid using gosax.Token, you can achieve even further performance improvements, potentially approaching twice the speed of the current implementation.
```
goos: darwin
goarch: arm64
pkg: github.com/vinser/flibgolite/pkg/fb2
cpu: Apple M2 Max
BenchmarkParseFB2/encoding/xml-12         	   66860	     17926 ns/op
BenchmarkParseFB2/encoding/xml-12         	   66856	     18006 ns/op
BenchmarkParseFB2/encoding/xml-12         	   66138	     17942 ns/op
BenchmarkParseFB2/encoding/xml-12         	   66567	     17920 ns/op
BenchmarkParseFB2/encoding/xml-12         	   66526	     17939 ns/op
BenchmarkParseFB2/gosax-12                	  521638	      2819 ns/op
BenchmarkParseFB2/gosax-12                	  477084	      2912 ns/op
BenchmarkParseFB2/gosax-12                	  441318	      2633 ns/op
BenchmarkParseFB2/gosax-12                	  482030	      2610 ns/op
BenchmarkParseFB2/gosax-12                	  451369	      2601 ns/op
PASS
```
