### ISSUE TITLE
gosax.EventEnd is not emitted for self-closing tags

### ISSUE THREAD

**Issue by leocassarani** [orisano/gosax#3]
Hi, thanks for writing this package, we've been investigating migrating to it from `encoding/xml` as it seems to provide a very significant performance boost.

However, we've discovered that gosax doesn't currently handle self-closing tags in the way we would have expected. In the example below, I would expect to get both a `gosax.EventStart` followed by `gosax.EventEnd` for the `<element/>` tag, but only the former is received.

```go
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/orisano/gosax"
)

func main() {
	xmlData := `<root><element /></root>`
	r := gosax.NewReader(strings.NewReader(xmlData))

loop:
	for {
		e, err := r.Event()
		if err != nil {
			log.Fatal(err)
		}

		switch e.Type() {
		case gosax.EventStart:
			name, _ := gosax.Name(e.Bytes)
			fmt.Printf("Entering %s\n", string(name))
		case gosax.EventEnd:
			name, _ := gosax.Name(e.Bytes)
			fmt.Printf("Exiting %s\n", string(name))
		case gosax.EventEOF:
			break loop
		}
	}
}

// Output:
// Entering root
// Entering element
// Exiting /root
```

At present, we've worked around this in our prototype by defining a `isSelfClosingTag()` function and triggering our tag-end logic if it returns true. However, a more robust solution would also strip out any whitespace between the `/` and the `>` characters.

```go
func isSelfClosingTag(b []byte) bool {
	return bytes.HasSuffix(b, []byte("/>"))
}
```

Additionally, as can be seen in the output above, it's surprising that `gosax.Name(e.Bytes)` includes the leading `/` for a `gosax.EventEnd` event. This isn't as big an issue as it's easy to strip it out, but it was another surprise we got when integrating with this package.

Let me know if you have any questions, happy to elaborate on what we're trying to do.

**Comment by orisano** [comment]
Fixed in commit b77e2f7. Please test the EmitSelfClosingTag feature!

**Comment by orisano** [comment]
@leocassarani Thank you for trying out this library. Please let me know if you notice any performance improvements.

**Comment by leocassarani** [comment]
Thanks @orisano, that's brilliant. I've just tested the new `EmitSelfClosingTag` field and it seems to work exactly as I would have expected 😄 Happy to close this issue if you are. I think we're going to be seeing a more than 2x performance boost compared to `encoding/xml` which is fantastic. Thanks again for building this library!

**Comment by vinser** [comment]
This helped me a lot! Tnx
