### ISSUE TITLE
panic: slice bounds out of range when reading a sufficiently large text node

### ISSUE THREAD

**Issue by leocassarani** [orisano/gosax#6]
Hi again, we've been seeing some panics in our application and after a lot of digging I've tracked it down to a potential bug in the buffered reader within gosax.

In short, our application reads XML from a zip file (using the standard library's `archive/zip`), which means that each `Read()` produces a relatively small amount of bytes compared to reading straight from a file or an in-memory buffer. Specifically, in our testing, each `Read()` call to the `io.ReadCloser` returned by [`zip.File.Open()`](https://pkg.go.dev/archive/zip#File.Open) seems to consistently fill only 32,768 bytes of the buffer (i.e. 32Kib).

After further investigation, we found out that if an XML text node is sufficiently larger than the amount of bytes produced by `Read()`, that will reliably trigger the "slice bounds out of range" panic within gosax. This seems to happen regardless of the actual sizes involved, as long as the text node is at least just under twice as large as the buffer read size.

To simplify debugging, I've written a minimal reproduction case, which should reliably trigger the problem. In this code, we artificially limit each `Read()` to 1024 bytes, but the file we're parsing has a text node containing 2045 bytes, the minimum required to trigger a panic.

```go
package main

import (
	"io"
	"log"
	"strings"

	"github.com/orisano/gosax"
)

func main() {
	xml := `<x>` + strings.Repeat("X", 2045) + `</x>`

	sax := gosax.NewReader(&atMostReader{
		r:     strings.NewReader(xml),
		limit: 1024,
	})

	for {
		e, err := sax.Event()
		if err != nil {
			log.Fatal(err)
		}

		if e.Type() == gosax.EventEOF {
			break
		}
	}
}

type atMostReader struct {
	r     io.Reader
	limit int
}

func (r *atMostReader) Read(p []byte) (int, error) {
	if len(p) <= r.limit {
		return r.r.Read(p)
	}
	return r.r.Read(p[:r.limit])
}
```

When running this code, I get the following:

```
$ go run main.go
panic: runtime error: slice bounds out of range [3066:2049]

goroutine 1 [running]:
github.com/orisano/gosax.readText(0xc000066180)
        …/golang/pkg/mod/github.com/orisano/gosax@v0.0.0-20240715153108-1fcab6934d6e/gosax.go:352 +0xff
github.com/orisano/gosax.(*Reader).stateInsideText(0xc000066180)
        …/golang/pkg/mod/github.com/orisano/gosax@v0.0.0-20240715153108-1fcab6934d6e/gosax.go:114 +0x1e
github.com/orisano/gosax.(*Reader).Event(...)
        …/golang/pkg/mod/github.com/orisano/gosax@v0.0.0-20240715153108-1fcab6934d6e/gosax.go:92
main.main()
        main.go:20 +0x224
exit status 2
```

I appreciate this is quite an intricate bug, so let me know if anything's unclear. Thank you for all your help with the issues we've found so far!

**Comment by orisano** [comment]
Thank you for the report! I apologize for any inconvenience caused. This issue has been fixed.

**Comment by glenjamin** [comment]
Ah damn, you got there before me, I'd just typed this message out to my colleague @leocassarani !

- The offset in `readText`'s loop is trying to avoid checking the same bytes multiple times after the buffer has been extended
- The content check scans `w[offset:]` until it finds `<`
- If it doesn't match then `offset` is updated by `len(w)` but that's more than what we've checked when `offset != 0`
- This only occurs on the second iteration of the loop
- Which causes the third iteration of the loop to panic with the bounds error
- The correct line should be `offset = len(w)`

Thanks for your work on this, and the quick fixes.

We're currently rolling this out into production alongside our existing parser and comparing results before switching over.

Your new parser is significantly faster, hopefully we'll be able to help iron out any remaining issues.
